# Generated by Django 5.2 on 2025-08-13 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_remove_client_contact2'),
        ('factures', '0002_alter_invoice_options_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='clients.contact'),
        ),
    ]
