# Generated by Django 5.1.7 on 2025-03-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_address'),
        ('factures', '0002_alter_invoice_affaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(on_delete=models.SET('client.client'), related_name='invoices', to='clients.client'),
        ),
    ]
