# Generated by Django 5.1.7 on 2025-03-22 10:59

import clients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_address'),
        ('factures', '0003_alter_invoice_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(on_delete=models.CASCADE, related_name='invoices', to='clients.client'),
            # field=models.ForeignKey(on_delete=models.SET(clients.models.Client.gt_entity_name), related_name='invoices', to='clients.client'),
        ),
    ]
