# Generated by Django 5.1.7 on 2025-03-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0004_alter_invoice_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='client_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
