# Generated by Django 5.2.5 on 2025-08-14 13:17

import factures.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0004_invoice_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='facture_pdf',
            field=models.FileField(blank=True, null=True, upload_to='factures', validators=[factures.models.validateur_extentions]),
        ),
    ]
