# Generated by Django 5.2.5 on 2025-08-15 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affaires', '0005_affaire_author'),
        ('factures', '0005_invoice_facture_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='affaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='affaires.affaire'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='factures.invoice'),
        ),
    ]
