# Generated by Django 5.1.7 on 2025-03-22 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_address'),
        ('factures', '0005_invoice_client_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='client_name',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='clients.client'),
        ),
    ]
