# Generated by Django 5.1.7 on 2025-03-22 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_client_options'),
        ('factures', '0006_remove_invoice_client_name_alter_invoice_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='clients.client'),
        ),
    ]
