# Generated by Django 5.1.7 on 2025-03-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_client_zip_code_alter_client_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='zip_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
