# Generated by Django 5.2 on 2025-06-17 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_options_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contact2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='clients.contact'),
        ),
    ]
