# Generated by Django 5.2 on 2025-08-13 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_contact2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='contact2',
        ),
    ]
