# Generated by Django 5.1.7 on 2025-03-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='entity_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
