# Generated by Django 5.2 on 2025-08-13 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_remove_client_contact2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['nom'], 'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
    ]
