# Generated by Django 5.2.5 on 2025-08-14 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affaires', '0005_affaire_author'),
        ('clients', '0005_alter_contact_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contact',
            name='unique_principal_contact_per_client',
        ),
        migrations.AddField(
            model_name='contact',
            name='affaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='affaires.affaire'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(condition=models.Q(('is_principal', True)), fields=('affaire', 'is_principal'), name='unique_principal_contact_per_affaire'),
        ),
    ]
