# Generated by Django 5.2.5 on 2025-08-14 15:43

from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_remove_contact_unique_principal_contact_per_client_and_more'),
    ]

    operations = [
        # Supprimer l'ancien champ client
        migrations.RemoveField(
            model_name='contact',
            name='client',
        ),
        # Modifier le champ affaire pour le rendre obligatoire
        migrations.AlterField(
            model_name='contact',
            name='affaire',
            field=django.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='affaires.affaire'),
        ),
    ]
