# Generated by Django 5.1.7 on 2025-03-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affaires', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affaire',
            options={'verbose_name': 'Affaire', 'verbose_name_plural': 'Affaires'},
        ),
        migrations.AddField(
            model_name='affaire',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
