# Generated by Django 5.1.7 on 2025-03-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('affaires', '0001_initial'),
        ('factures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='affaire',
            name='factures',
            field=models.ManyToManyField(blank=True, null=True, related_name='affaires', to='factures.invoice'),
        ),
    ]
