# Generated by Django 5.2 on 2025-05-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affaires', '0003_affaire_client_entity_name_alter_affaire_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affaire',
            name='factures',
        ),
        migrations.AlterField(
            model_name='affaire',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
