# Generated by Django 5.1.7 on 2025-03-20 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affaires', '0003_affaire_facture'),
        ('factures', '0002_alter_invoice_affaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affaire',
            name='facture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affaires', to='factures.invoice'),
        ),
    ]
