# Generated by Django 5.1.7 on 2025-03-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affaires', '0004_alter_affaire_facture'),
        ('factures', '0002_alter_invoice_affaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affaire',
            name='facture',
        ),
        migrations.AddField(
            model_name='affaire',
            name='factures',
            field=models.ManyToManyField(related_name='affaires', to='factures.invoice'),
        ),
    ]
