# Generated by Django 5.1.7 on 2025-03-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affaires', '0005_remove_affaire_facture_affaire_factures'),
        ('factures', '0002_alter_invoice_affaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affaire',
            name='factures',
            field=models.ManyToManyField(blank=True, null=True, related_name='affaires', to='factures.invoice'),
        ),
    ]
